### ISSUE TITLE
Lorem Ipsum not working on window 10 machine. 

### ISSUE THREAD

**Issue by tehtarik1913** [lkcampbell/brackets-lorem-ipsum#14]
The extension does not function on brackets after adding extension. Tried removing, reinstalling and run brackets again. The `Ctrl-Shift-L`  short cut has assigned to Beautify
 Other keys like `lorem_wrap40` `lorem_html_wrap40` `lorem_nowrap_wrap40` are not functioning. 

However, the other extension Lorem Breizhum[https://github.com/YoruNoHikage/brackets-lorem-breizhum](url) is working.

**Comment by Christian1998** [comment]
Same here with Mac OS X, gonna uninstall it

**Comment by lkcampbell** [comment]
Conflicts with key bindings are inevitable with all of the Brackets extensions available.

Your best bet is to reassign the shortcut. See:

https://github.com/lkcampbell/brackets-lorem-ipsum#custom-key-bindings
