### ISSUE TITLE
Conflict with Beautify

### ISSUE THREAD

**Issue by gustaveco** [lkcampbell/brackets-lorem-ipsum#15]
in Brackets  1.14.1-17752 (release-1.14.1 959fed135) . When i installed (endabled) Beautify the keybinding of "lorem"+Ctr+Shifth+L does not work. I disabled Beautfy and it worked again.

**Comment by lkcampbell** [comment]
Extension authors don't have any control over key mapping conflicts with other extensions.

The solution is to change the custom key binding of this extension or the other conflicting extension:
https://github.com/lkcampbell/brackets-lorem-ipsum#custom-key-bindings
