### ISSUE TITLE
Customizable keybinding

### ISSUE THREAD

**Issue by divsmith** [lkcampbell/brackets-lorem-ipsum#6]
It would be nice for users to be able to customize the keybinding for expanding the lorem text.

**Comment by lkcampbell** [comment]
Also, add in documentation on the command id for the extension an example of how to add shortcut keys for that command.

**Comment by MarcoWilli** [comment]
Is this already possible right now?
I don´t see the binding to tab key, only for the emmet extension.

**Comment by lkcampbell** [comment]
@MarcoWilli, No, not possible yet. I need to fix the code first, then it will be possible. Hopefully this weekend.

**Comment by LowellMontgomery** [comment]
Yeah... without an alternate key-binding, this is not useful for me. There is in-built lorem-ipsum (or maybe part of Emmet) that is inserted via tab-trigger, but with Emmet and tab-trigger, it will just wrap the lorem text as tags... not ideal. (e.g. <lorem_s2></lorem_s2> As someone with years of muscle memory for tab-triggering tags (in Textmate / Mac) I would rather not make the Emmet trigger anything but the tag. Lorem triggering should be something else and be less disruptive to workflow.

**Comment by lkcampbell** [comment]
I'll take a look at this soon. Shouldn't be too hard to implement. Not this weekend but probably next weekend.

**Comment by LowellMontgomery** [comment]
Thanks for your response, @lkcampbell.  As I said, I had the same thought that it "shouldn't be too hard to implement", so I'll fork this and hold the issue in mind and see if I have any bright ideas about a good way to do accomplish this. :wink:

**Comment by lkcampbell** [comment]
Fixed in version 1.1.0.
