### ISSUE TITLE
plugin to change the Persian language

### ISSUE THREAD

**Issue by msmaxsoft** [lkcampbell/brackets-lorem-ipsum#8]
Hi
I want the plugin to change the Persian language
Do I have to do?

I have a question
Text file that is inside a folder? What is the purpose?

To change (if it's possible to have) what should the files changed?

tnk's

**Comment by lkcampbell** [comment]
The text file is used with the _fortune option. It is a bunch of random phrases from an old Unix program called fortune. The extension pulls a random phrase from the file and writes it into the text editor.
