### ISSUE TITLE
Feature Request - default settings

### ISSUE THREAD

**Issue by meeple142** [lkcampbell/brackets-lorem-ipsum#9]
Thanks for the awesome plugin!
It would be great if there was a way to set default settings, im thinking just a json obj somewhere -- just not project specific -- so that you could just type lorem[tab] and it would follow the users default settings.

Again Thanks!

**Comment by lkcampbell** [comment]
@meeple142, sorry for taking so long to get back to you. Do you mean, like, if you always want `lorem_html_wrap40` every time you type `lorem` and hit tab, you could set that as a preference?

**Comment by meeple142** [comment]
Yep! You could just have the preffrence be a string like lorem_html_wrap40 or any other valid one and not a huge json obj. Also I don't type lorem[tab] very offten so that that would be great for me. But maybe others do? So if you had to make it lorem_[tab] that would be fine too. Up to you.:)

Then of course if you wanted something other than your preference you just use your plug in like normal.

Thanks again÷

**Comment by lkcampbell** [comment]
Added in version 1.1.2. See the [two new preferences](https://github.com/lkcampbell/brackets-lorem-ipsum#extension-preferences).

**Comment by meeple142** [comment]
Awesome thank you!

**Comment by lkcampbell** [comment]
@meeple142 no problem. It's a good idea, I'm using it myself.

Sorry it took so long to add this but I finally have Brackets coding time again :).
